### ISSUE TITLE
How to visit multiple pages in one session?

### ISSUE THREAD

**Issue by balmasi** [travist/jquery.go.js#29]
Phantom/jquery.go work fine for whatever page I'm on, but as soon as I want to .visit another page it crashes with a broken pipe, saying:

jquery.go ERROR: Operation canceled
jquery.go ERROR: Operation canceled
jquery.go ERROR: Operation canceled 
.
.
.

Any Ideas why this is happening?

**Comment by travist** [comment]
What is happening is that you have AJAX being performed on the page that you are navigating away from and when you navigate away from a page during the middle of an AJAX method, it will throw an error saying that the "Operation canceled"
