### ISSUE TITLE
append

### ISSUE THREAD

**Issue by flipflopsimsommer** [travist/jquery.go.js#30]
ist there a way to use jquerygo.append?

**Comment by travist** [comment]
I cannot think of a reason why you would want to append an HTML element within a test or an automation task. What is your use case?

**Comment by flipflopsimsommer** [comment]
i need to execute some js code on the website, i cannot execute over jquerygo because of some missing features like checking if a dom exists.
as a workarround i thouhgt i might convert them to string, put them in a script element and append them to my html element.

**Comment by travist** [comment]
A better way to do that is to just use PhantomJS to evaluate javascript on the page, like so.

```
  // Get the page.
  $.getPage(function(page) {
    page.evaluate(function(args) {
      console.log('We are executing JavaScript on the page! Here are some arguments...');
      console.log(args);
      return {returnParam: 'returnValue'};;
    }, function(retVal) {
      console.log('We are done executing! The value of the return is.');
      console.log(retVal);
    }, {
      someArg: 'value_of_arg'
    });
});
```

**Comment by flipflopsimsommer** [comment]
wow, i didn't know, thx  :+1:
