### ISSUE TITLE
Multiple calls to .visit() in a mocha test environment seems to fail.

### ISSUE THREAD

**Issue by dcbartlett** [travist/jquery.go.js#9]
When trying to automate some tests with jquery.go and mocha, it seems that the second (and subsequent) calls to $.visit() do not fire the callback.  Since they are not firing the callback, i'm going to assume that they are not being successfully triggered?

If anyone can give some insight on this, that would be great.  Below is the mocha test.  I run with _**mocha -R spec test/test.js**_

``` javascript
// Libraries
var $ = require('jquerygo');
var assert = require("assert");

describe('GOOGLE', function() {
    describe('should', function() {
        it('save a screenshot.', function(done) {
            this.timeout(15000);
            $.visit('https://www.google.com', function() {
                $.capture(__dirname + '/../screenshots/google.png', function(){
                    $.close();
                    done();
                });
            });
        });
        it('search for cats', function(done) {
            this.timeout(15000);
            console.log('i\'m going to search for cats now');
            $.visit('https://www.google.com', function() {
                console.log('i loaded the page!');
                $('input#gbqfq[name=q]').val('cats',function(){
                    console.log('i changed the input!');
                    $.capture(__dirname + '/../screenshots/google_cats.png', function(){
                        $.close();
                        done()
                    });
                });
            });
        });
    });
});
```

**Comment by damgad** [comment]
Could you please explain why it's a problem to visit pages sequentially? I can understand that it's impossible to request multiple pages simultanously, but it's not the case in dcbartlett's code.

Mocha runs test synchronously one by one. `search for cats` test case is called after the first `done();` (that even means - after the first `$.close();`). Why it's impossible to visit another page after the first one was received and screenshot taken?

How async.js would help? Isn't already the second page request called after the first finished?

**Comment by dcbartlett** [comment]
You know, i know this is an old thread, but now that i look back on it, i agree with damgad, since i'm using mocha in a synchronous fashion, why wouldn't using it the way my original post is setup work?
